ChibiOS: QEI Driver
QEI Driver
HAL » Normal Drivers
Quadrature Encoder Interface.
Detailed Description
Quadrature Encoder Interface.
Precondition
In order to use the QEI driver the HAL_USE_QEI option must be enabled in halconf.h.
Macro Functions
void qeiInit (void)
QEI Driver initialization.
void qeiObjectInit (QEIDriver *qeip)
Initializes the standard part of a QEIDriver structure.
void qeiStart (QEIDriver *qeip, const QEIConfig *config)
Configures and activates the QEI peripheral.
void qeiStop (QEIDriver *qeip)
Deactivates the QEI peripheral.
void qeiEnable (QEIDriver *qeip)
Enables the quadrature encoder interface.
void qeiDisable (QEIDriver *qeip)
Disables the quadrature encoder interface.
qeicnt_t qeiGetCount (QEIDriver *qeip)
Returns the counter value.
void qeiSetCount (QEIDriver *qeip, qeicnt_t value)
Set counter value.
qeidelta_t qeiAdjustI (QEIDriver *qeip, qeidelta_t delta)
Adjust the counter by delta.
qeidelta_t qeiUpdate (QEIDriver *qeip)
Returns the counter delta from last reading.
qeidelta_t qeiUpdateI (QEIDriver *qeip)
Returns the counter delta from last reading.
#define qeiEnableI(qeip) qei_lld_enable(qeip)
Enables the input capture.
#define qeiDisableI(qeip) qei_lld_disable(qeip)
Disables the input capture.
#define qeiGetCountI(qeip) qei_lld_get_count(qeip)
Returns the counter value.
Typedefs
typedef struct QEIDriver QEIDriver
Type of a structure representing an QEI driver.
typedef void(* qeicallback_t) (QEIDriver *qeip)
QEI notification callback type.
Functions
static bool qei_adjust_count (qeicnt_t *count, qeidelta_t *delta, qeicnt_t min, qeicnt_t max, qeioverflow_t mode)
Helper for correclty handling overflow/underflow.
qeidelta_t qeiAdjust (QEIDriver *qeip, qeidelta_t delta)
Adjust the counter by delta.
Enumerations
enum qeistate_t { QEI_UNINIT = 0, QEI_STOP = 1, QEI_READY = 2, QEI_ACTIVE = 3 }
Driver state machine possible states.
enum qeioverflow_t { QEI_OVERFLOW_WRAP = 0 }
Driver possible handling of counter overflow/underflow.
Macro Definition Documentation
qeiEnableI
#define qeiEnableI (qeip) qei_lld_enable(qeip)
Enables the input capture.
Parameters
[in] qeip pointer to the QEIDriver object
Function Class:^^This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 113 of file hal_qei.h.
qeiDisableI
#define qeiDisableI (qeip) qei_lld_disable(qeip)
Disables the input capture.
Parameters
[in] qeip pointer to the QEIDriver object
Function Class:^^This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 122 of file hal_qei.h.
qeiGetCountI
#define qeiGetCountI (qeip) qei_lld_get_count(qeip)
Returns the counter value.
Parameters
[in] qeip pointer to the QEIDriver object
Returns
The current counter value.
Function Class:^^This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 132 of file hal_qei.h.
Referenced by qeiGetCount().
Typedef Documentation
QEIDriver
typedef struct QEIDriver QEIDriver
Type of a structure representing an QEI driver.
Definition at line 59 of file hal_qei.h.
qeicallback_t
typedef void(* qeicallback_t) (QEIDriver *qeip)
QEI notification callback type.
Parameters
[in] qeip pointer to a QEIDriver object
Definition at line 66 of file hal_qei.h.
Enumeration Type Documentation
qeistate_t
enum qeistate_t
Driver state machine possible states.
Enumerator
QEI_UNINIT
Not initialized.
QEI_STOP
Stopped.
QEI_READY
Ready.
QEI_ACTIVE
Active.
Definition at line 49 of file hal_qei.h.
qeioverflow_t
enum qeioverflow_t
Driver possible handling of counter overflow/underflow.
When counter is going to overflow, the new value is computed according to this mode in such a way that the counter will either wrap around, stay unchange or reach min/max
Note
All driver implementation should support the QEI_OVERFLOW_WRAP mode.
Mode QEI_OVERFLOW_DISCARD and QEI_OVERFLOW_MINMAX are included if QEI_USE_OVERFLOW_DISCARD and QEI_USE_OVERFLOW_MINMAX are set to TRUE in halconf_community.h and are not necessary supported by all drivers
Enumerator
QEI_OVERFLOW_WRAP
Counter value will wrap around.
Definition at line 84 of file hal_qei.h.
Function Documentation
qei_adjust_count()
static bool qei_adjust_count (qeicnt_t * count, qeidelta_t * delta, qeicnt_t min, qeicnt_t max, qeioverflow_t mode) inline static
Helper for correclty handling overflow/underflow.
Underflow/overflow will be handled according to mode: QEI_OVERFLOW_WRAP: counter value will wrap around. QEI_OVERFLOW_DISCARD: counter will not change QEI_OVERFLOW_MINMAX: counter will be updated upto min or max.
Note
This function is for use by low level driver.
Parameters
[in,out] count counter value
[in,out] delta adjustment value
[in] min minimum allowed value for counter
[in] max maximum allowed value for counter
[in] mode how to handle overflow
Returns
true if counter underflow/overflow occured or was due to occur
Definition at line 66 of file hal_qei.c.
References QEI_OVERFLOW_WRAP.
Referenced by qeiAdjustI().
qeiInit()
void qeiInit (void)
QEI Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:^^Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 142 of file hal_qei.c.
Referenced by halInit().
qeiObjectInit()
void qeiObjectInit (QEIDriver * qeip)
Initializes the standard part of a QEIDriver structure.
Parameters
[out] qeip pointer to the QEIDriver object
Function Class:^^Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 154 of file hal_qei.c.
References QEI_STOP.
qeiStart()
void qeiStart (QEIDriver * qeip, const QEIConfig * config)
Configures and activates the QEI peripheral.
Parameters
[in] qeip pointer to the QEIDriver object
[in] config pointer to the QEIConfig object
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 169 of file hal_qei.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), QEI_READY, and QEI_STOP.
qeiStop()
void qeiStop (QEIDriver * qeip)
Deactivates the QEI peripheral.
Parameters
[in] qeip pointer to the QEIDriver object
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 189 of file hal_qei.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), QEI_READY, and QEI_STOP.
qeiEnable()
void qeiEnable (QEIDriver * qeip)
Enables the quadrature encoder interface.
Parameters
[in] qeip pointer to the QEIDriver object
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 208 of file hal_qei.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), QEI_ACTIVE, and QEI_READY.
qeiDisable()
void qeiDisable (QEIDriver * qeip)
Disables the quadrature encoder interface.
Parameters
[in] qeip pointer to the QEIDriver object
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 226 of file hal_qei.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), QEI_ACTIVE, and QEI_READY.
qeiGetCount()
qeicnt_t qeiGetCount (QEIDriver * qeip)
Returns the counter value.
Parameters
[in] qeip pointer to the QEIDriver object
Returns
The current counter value.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 246 of file hal_qei.c.
References osalSysLock(), osalSysUnlock(), and qeiGetCountI.
qeiSetCount()
void qeiSetCount (QEIDriver * qeip, qeicnt_t value)
Set counter value.
Parameters
[in] qeip pointer to the QEIDriver object.
[in] value the new counter value.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 264 of file hal_qei.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), QEI_ACTIVE, and QEI_READY.
qeiAdjust()
qeidelta_t qeiAdjust (QEIDriver * qeip, qeidelta_t delta)
Adjust the counter by delta.
Parameters
[in] qeip pointer to the QEIDriver object.
[in] delta the adjustement value.
Returns
the remaining delta (can occur during overflow).
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 283 of file hal_qei.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), QEI_ACTIVE, and qeiAdjustI().
qeiAdjustI()
qeidelta_t qeiAdjustI (QEIDriver * qeip, qeidelta_t delta)
Adjust the counter by delta.
Parameters
[in] qeip pointer to the QEIDriver object.
[in] delta the adjustement value.
Returns
the remaining delta (can occur during overflow).
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 303 of file hal_qei.c.
References qei_adjust_count().
Referenced by qeiAdjust().
qeiUpdate()
qeidelta_t qeiUpdate (QEIDriver * qeip)
Returns the counter delta from last reading.
Parameters
[in] qeip pointer to the QEIDriver object
Returns
The delta from last read.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 339 of file hal_qei.c.
References osalSysLock(), osalSysUnlock(), and qeiUpdateI().
qeiUpdateI()
qeidelta_t qeiUpdateI (QEIDriver * qeip)
Returns the counter delta from last reading.
Parameters
[in] qeip pointer to the QEIDriver object
Returns
The delta from last read.
Function Class:^^This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 357 of file hal_qei.c.
References osalDbgAssert, osalDbgCheck, osalDbgCheckClassI, QEI_ACTIVE, and QEI_READY.
Referenced by qeiUpdate().