ChibiOS: Synchronous Messages
Synchronous Messages
NIL Kernel
Detailed Description
Macro Functions
#define chMsgWaitS() chMsgWaitTimeoutS(TIME_INFINITE)
Suspends the thread and waits for an incoming message.
#define chMsgGet(tp) ((tp)->sntmsg)
Returns the message carried by the specified thread.
#define chMsgReleaseS(tp, msg)
Releases the thread waiting on top of the messages queue.
Functions
msg_t chMsgSend (thread_t *tp, msg_t msg)
Sends a message to the specified thread.
thread_t * chMsgWait (void)
Suspends the thread and waits for an incoming message.
thread_t * chMsgWaitTimeout (sysinterval_t timeout)
Suspends the thread and waits for an incoming message or a timeout to occur.
thread_t * chMsgWaitTimeoutS (sysinterval_t timeout)
Suspends the thread and waits for an incoming message or a timeout to occur.
void chMsgRelease (thread_t *tp, msg_t msg)
Releases a sender thread specifying a response message.
Macro Definition Documentation
chMsgWaitS
thread_t * chMsgWaitS () chMsgWaitTimeoutS(TIME_INFINITE)
Suspends the thread and waits for an incoming message.
Postcondition
After receiving a message the function chMsgGet() must be called in order to retrieve the message and then chMsgRelease() must be invoked in order to acknowledge the reception and send the answer.
Note
If the message is a pointer then you can assume that the data pointed by the message is stable until you invoke chMsgRelease() because the sending thread is suspended until then.
The reference counter of the sender thread is not increased, the returned pointer is a temporary reference.
Returns
A pointer to the thread carrying the message.
Function Class:^^This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 73 of file nil/include/chmsg.h.
chMsgGet
#define chMsgGet (tp) ((tp)->sntmsg)
Returns the message carried by the specified thread.
Precondition
This function must be invoked immediately after exiting a call to chMsgWait().
Parameters
[in] tp pointer to the thread
Returns
The message carried by the sender.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 85 of file nil/include/chmsg.h.
Referenced by chDelegateDispatch(), and chDelegateDispatchTimeout().
chMsgReleaseS
#define chMsgReleaseS (tp, msg)
Value:
do {                                         \
  (void) chSchReadyI(tp, msg);                                              \
  chSchRescheduleS();                                                       \
  } while (false)
Releases the thread waiting on top of the messages queue.
Precondition
Invoke this function only after a message has been received using chMsgWait().
Parameters
[in] tp pointer to the thread
[in] msg message to be returned to the sender
Function Class:^^This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 97 of file nil/include/chmsg.h.
Referenced by chMsgRelease().
Function Documentation
chMsgSend()
msg_t chMsgSend (thread_t * tp, msg_t msg)
Sends a message to the specified thread.
The sender is stopped until the receiver executes a chMsgRelease()after receiving the message.
Parameters
[in] tp the pointer to the thread
[in] msg the message
Returns
The answer message from chMsgRelease().
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 67 of file nil/src/chmsg.c.
References chDbgCheck, chSysLock, and nil.
chMsgWait()
thread_t * chMsgWait (void)
Suspends the thread and waits for an incoming message.
Postcondition
After receiving a message the function chMsgGet() must be called in order to retrieve the message and then chMsgRelease() must be invoked in order to acknowledge the reception and send the answer.
Note
If the message is a pointer then you can assume that the data pointed by the message is stable until you invoke chMsgRelease() because the sending thread is suspended until then.
The reference counter of the sender thread is not increased, the returned pointer is a temporary reference.
Returns
A pointer to the thread carrying the message.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 100 of file nil/src/chmsg.c.
References chMsgWaitS(), chSysLock, and chSysUnlock.
Referenced by chDelegateDispatch().
chMsgWaitTimeout()
thread_t * chMsgWaitTimeout (sysinterval_t timeout)
Suspends the thread and waits for an incoming message or a timeout to occur.
Postcondition
After receiving a message the function chMsgGet() must be called in order to retrieve the message and then chMsgRelease() must be invoked in order to acknowledge the reception and send the answer.
Note
If the message is a pointer then you can assume that the data pointed by the message is stable until you invoke chMsgRelease() because the sending thread is suspended until then.
The reference counter of the sender thread is not increased, the returned pointer is a temporary reference.
Parameters
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
A pointer to the thread carrying the message.
Return values
NULL if a timeout occurred.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 133 of file nil/src/chmsg.c.
References chMsgWaitTimeoutS(), chSysLock, and chSysUnlock.
Referenced by chDelegateDispatchTimeout().
chMsgWaitTimeoutS()
thread_t* chMsgWaitTimeoutS (sysinterval_t timeout)
Suspends the thread and waits for an incoming message or a timeout to occur.
Postcondition
After receiving a message the function chMsgGet() must be called in order to retrieve the message and then chMsgRelease() must be invoked in order to acknowledge the reception and send the answer.
Note
If the message is a pointer then you can assume that the data pointed by the message is stable until you invoke chMsgRelease() because the sending thread is suspended until then.
The reference counter of the sender thread is not increased, the returned pointer is a temporary reference.
Parameters
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_INFINITE no timeout.
Returns
A pointer to the thread carrying the message.
Return values
NULL if a timeout occurred.
Function Class:^^This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 165 of file nil/src/chmsg.c.
Referenced by chMsgWaitTimeout().
chMsgRelease()
void chMsgRelease (thread_t * tp, msg_t msg)
Releases a sender thread specifying a response message.
Precondition
Invoke this function only after a message has been received using chMsgWait().
Parameters
[in] tp pointer to the thread
[in] msg message to be returned to the sender
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 191 of file nil/src/chmsg.c.
References chDbgAssert, chMsgReleaseS, chSysLock, chSysUnlock, NIL_STATE_SNDMSGQ, and ch_thread::state.