ChibiOS: Registry
Registry
RT Kernel
Detailed Description
Threads Registry related APIs and services.
Operation mode
The Threads Registry is a double linked list that holds all the active threads in the system.
Operations defined for the registry:
First, returns the first, in creation order, active thread in the system.
Next, returns the next, in creation order, active thread in the system.
The registry is meant to be mainly a debug feature, for example, using the registry a debugger can enumerate the active threads in any given moment or the shell can print the active threads and their state.
Another possible use is for centralized threads memory management, terminating threads can pulse an event source and an event handler can perform a scansion of the registry in order to recover the memory.
Precondition
In order to use the threads registry the CH_CFG_USE_REGISTRY option must be enabled in chconf.h.
Macros
#define REG_HEADER(oip) (&ch_system.reglist.queue)
Access to the registry list header.
#define REG_REMOVE(tp) (void) ch_queue_dequeue(&(tp)->rqueue)
Removes a thread from the registry list.
#define REG_INSERT(oip, tp) ch_queue_insert(REG_HEADER(oip), &(tp)->rqueue)
Adds a thread to the registry list.
Data Structures
struct chdebug_t
ChibiOS/RT memory signature record.
Functions
thread_t * chRegFirstThread (void)
Returns the first thread in the system.
thread_t * chRegNextThread (thread_t *tp)
Returns the thread next to the specified one.
thread_t * chRegFindThreadByName (const char *name)
Retrieves a thread pointer by name.
thread_t * chRegFindThreadByPointer (thread_t *tp)
Confirms that a pointer is a valid thread pointer.
thread_t * chRegFindThreadByWorkingArea (stkalign_t *wa)
Confirms that a working area is being used by some active thread.
static void __reg_object_init (registry_t *rp)
Initializes a registry.
static void chRegSetThreadName (const char *name)
Sets the current thread name.
static const char * chRegGetThreadNameX (thread_t *tp)
Returns the name of the specified thread.
static void chRegSetThreadNameX (thread_t *tp, const char *name)
Changes the name of the specified thread.
Macro Definition Documentation
REG_HEADER
#define REG_HEADER (oip) (&ch_system.reglist.queue)
Access to the registry list header.
Definition at line 98 of file chregistry.h.
Referenced by chRegFirstThread(), and chRegNextThread().
REG_REMOVE
#define REG_REMOVE (tp) (void) ch_queue_dequeue(&(tp)->rqueue)
Removes a thread from the registry list.
Note
This macro is not meant for use in application code.
Parameters
[in] tp thread to remove from the registry
Definition at line 109 of file chregistry.h.
Referenced by chThdExitS(), and chThdRelease().
REG_INSERT
#define REG_INSERT (oip, tp) ch_queue_insert(REG_HEADER(oip), &(tp)->rqueue)
Adds a thread to the registry list.
Note
This macro is not meant for use in application code.
Parameters
[in] oip pointer to the OS instance
[in] tp thread to add to the registry
Definition at line 118 of file chregistry.h.
Referenced by __thd_object_init().
Function Documentation
chRegFirstThread()
thread_t * chRegFirstThread (void)
Returns the first thread in the system.
Returns the most ancient thread in the system, usually this is the main thread unless it terminated. A reference is added to the returned thread in order to make sure its status is not lost.
Note
This function cannot return NULL because there is always at least one thread in the system.
Returns
A reference to the most ancient thread.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 159 of file chregistry.c.
References __CH_OFFSETOF, chSysLock, chSysUnlock, currcore, ch_thread::refs, REG_HEADER, and threadref.
Referenced by chRegFindThreadByName(), chRegFindThreadByPointer(), and chRegFindThreadByWorkingArea().
chRegNextThread()
thread_t * chRegNextThread (thread_t * tp)
Returns the thread next to the specified one.
The reference counter of the specified thread is decremented and the reference counter of the returned thread is incremented.
Parameters
[in] tp pointer to the thread
Returns
A reference to the next thread.
Return values
NULL if there is no next thread.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 187 of file chregistry.c.
References __CH_OFFSETOF, chDbgAssert, chSysLock, chSysUnlock, chThdRelease(), currcore, ch_queue::next, ch_thread::refs, REG_HEADER, ch_thread::rqueue, and threadref.
Referenced by chRegFindThreadByName(), chRegFindThreadByPointer(), and chRegFindThreadByWorkingArea().
chRegFindThreadByName()
thread_t * chRegFindThreadByName (const char * name)
Retrieves a thread pointer by name.
Note
The reference counter of the found thread is increased by one so it cannot be disposed incidentally after the pointer has been returned.
Parameters
[in] name the thread name
Returns
A pointer to the found thread.
Return values
NULL if a matching thread has not been found.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 230 of file chregistry.c.
References chRegFirstThread(), chRegGetThreadNameX(), and chRegNextThread().
chRegFindThreadByPointer()
thread_t * chRegFindThreadByPointer (thread_t * tp)
Confirms that a pointer is a valid thread pointer.
Note
The reference counter of the found thread is increased by one so it cannot be disposed incidentally after the pointer has been returned.
Parameters
[in] tp pointer to the thread
Returns
A pointer to the found thread.
Return values
NULL if a matching thread has not been found.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 257 of file chregistry.c.
References chRegFirstThread(), and chRegNextThread().
chRegFindThreadByWorkingArea()
thread_t * chRegFindThreadByWorkingArea (stkalign_t * wa)
Confirms that a working area is being used by some active thread.
Note
The reference counter of the found thread is increased by one so it cannot be disposed incidentally after the pointer has been returned.
Parameters
[in] wa pointer to a static working area
Returns
A pointer to the found thread.
Return values
NULL if a matching thread has not been found.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 286 of file chregistry.c.
References chRegFirstThread(), chRegNextThread(), and chThdGetWorkingAreaX().
Referenced by chThdCreate(), chThdCreateStatic(), and chThdCreateSuspended().
__reg_object_init()
static void __reg_object_init (registry_t * rp) inline static
Initializes a registry.
Note
Internal use only.
Parameters
[out] rp pointer to a registry_t structure
Function Class:^^Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 151 of file chregistry.h.
References ch_queue_init(), and ch_registry::queue.
Referenced by chInstanceObjectInit().
chRegSetThreadName()
static void chRegSetThreadName (const char * name) inline static
Sets the current thread name.
Precondition
This function only stores the pointer to the name if the option CH_CFG_USE_REGISTRY is enabled else no action is performed.
Parameters
[in] name thread name as a zero terminated string
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 165 of file chregistry.h.
References __sch_get_currthread.
chRegGetThreadNameX()
static const char* chRegGetThreadNameX (thread_t * tp) inline static
Returns the name of the specified thread.
Precondition
This function only returns the pointer to the name if the option CH_CFG_USE_REGISTRY is enabled else NULL is returned.
Parameters
[in] tp pointer to the thread
Returns
Thread name as a zero terminated string.
Return values
NULL if the thread name has not been set.
Definition at line 185 of file chregistry.h.
References ch_thread::name.
Referenced by chRegFindThreadByName().
chRegSetThreadNameX()
static void chRegSetThreadNameX (thread_t * tp, const char * name) inline static
Changes the name of the specified thread.
Precondition
This function only stores the pointer to the name if the option CH_CFG_USE_REGISTRY is enabled else no action is performed.
Parameters
[in] tp pointer to the thread
[in] name thread name as a zero terminated string
Function Class:^^This is an X-Class API, this function can be invoked from any context.
Definition at line 205 of file chregistry.h.
References ch_thread::name.