ChibiOS: Semaphores
Semaphores
NIL Kernel
Detailed Description
Semaphores macros
#define __SEMAPHORE_DATA(name, n) {n}
Data part of a static semaphore initializer.
#define SEMAPHORE_DECL(name, n) semaphore_t name = __SEMAPHORE_DATA(name, n)
Static semaphore initializer.
Macro Functions
#define chSemObjectInit(sp, n) ((sp)->cnt = (n))
Initializes a semaphore with the specified counter value.
#define chSemReset(sp, n) chSemResetWithMessage(sp, n, MSG_RESET)
Performs a reset operation on the semaphore.
#define chSemResetI(sp, n) chSemResetWithMessageI(sp, n, MSG_RESET)
Performs a reset operation on the semaphore.
#define chSemWait(sp) chSemWaitTimeout(sp, TIME_INFINITE)
Performs a wait operation on a semaphore.
#define chSemWaitS(sp) chSemWaitTimeoutS(sp, TIME_INFINITE)
Performs a wait operation on a semaphore.
#define chSemFastWaitI(sp) ((sp)->cnt--)
Decreases the semaphore counter.
#define chSemFastSignalI(sp) ((sp)->cnt++)
Increases the semaphore counter.
#define chSemGetCounterI(sp) ((sp)->cnt)
Returns the semaphore counter current value.
Functions
msg_t chSemWaitTimeout (semaphore_t *sp, sysinterval_t timeout)
Performs a wait operation on a semaphore with timeout specification.
msg_t chSemWaitTimeoutS (semaphore_t *sp, sysinterval_t timeout)
Performs a wait operation on a semaphore with timeout specification.
void chSemSignal (semaphore_t *sp)
Performs a signal operation on a semaphore.
void chSemSignalI (semaphore_t *sp)
Performs a signal operation on a semaphore.
void chSemResetWithMessage (semaphore_t *sp, cnt_t n, msg_t msg)
Performs a reset operation on the semaphore.
void chSemResetWithMessageI (semaphore_t *sp, cnt_t n, msg_t msg)
Performs a reset operation on the semaphore.
Macro Definition Documentation
__SEMAPHORE_DATA
#define __SEMAPHORE_DATA (name, n) {n}
Data part of a static semaphore initializer.
This macro should be used when statically initializing a semaphore that is part of a bigger structure.
Parameters
[in] name the name of the semaphore variable
[in] n the counter initial value, this value must be non-negative
Definition at line 66 of file nil/include/chsem.h.
SEMAPHORE_DECL
#define SEMAPHORE_DECL (name, n) semaphore_t name = __SEMAPHORE_DATA(name, n)
Static semaphore initializer.
Statically initialized semaphores require no explicit initialization using chSemInit().
Parameters
[in] name the name of the semaphore variable
[in] n the counter initial value, this value must be non-negative
Definition at line 77 of file nil/include/chsem.h.
chSemObjectInit
#define chSemObjectInit (sp, n) ((sp)->cnt = (n))
Initializes a semaphore with the specified counter value.
Parameters
[out] sp pointer to a semaphore_t structure
[in] n initial value of the semaphore counter. Must be non-negative.
Function Class:^^Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 93 of file nil/include/chsem.h.
chSemReset
#define chSemReset (sp, n) chSemResetWithMessage(sp, n, MSG_RESET)
Performs a reset operation on the semaphore.
Postcondition
After invoking this function all the threads waiting on the semaphore, if any, are released and the semaphore counter is set to the specified, non negative, value.
Note
This function implicitly sends MSG_RESET as message.
Parameters
[in] sp pointer to a semaphore_t structure
[in] n the new value of the semaphore counter. The value must be non-negative.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 108 of file nil/include/chsem.h.
Referenced by chBSemReset().
chSemResetI
#define chSemResetI (sp, n) chSemResetWithMessageI(sp, n, MSG_RESET)
Performs a reset operation on the semaphore.
Postcondition
After invoking this function all the threads waiting on the semaphore, if any, are released and the semaphore counter is set to the specified, non negative, value.
This function does not reschedule so a call to a rescheduling function must be performed before unlocking the kernel. Note that interrupt handlers always reschedule on exit so an explicit reschedule must not be performed in ISRs.
Note
This function implicitly sends MSG_RESET as message.
Parameters
[in] sp pointer to a semaphore_t structure
[in] n the new value of the semaphore counter. The value must be non-negative.
Function Class:^^This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 127 of file nil/include/chsem.h.
chSemWait
#define chSemWait (sp) chSemWaitTimeout(sp, TIME_INFINITE)
Performs a wait operation on a semaphore.
Parameters
[in] sp pointer to a semaphore_t structure
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
CH_MSG_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
CH_MSG_RST if the semaphore has been reset using chSemReset().
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 141 of file nil/include/chsem.h.
chSemWaitS
#define chSemWaitS (sp) chSemWaitTimeoutS(sp, TIME_INFINITE)
Performs a wait operation on a semaphore.
Parameters
[in] sp pointer to a semaphore_t structure
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
CH_MSG_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
CH_MSG_RST if the semaphore has been reset using chSemReset().
Function Class:^^This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 155 of file nil/include/chsem.h.
chSemFastWaitI
#define chSemFastWaitI (sp) ((sp)->cnt--)
Decreases the semaphore counter.
This macro can be used when the counter is known to be positive.
Parameters
[in] sp pointer to a semaphore_t structure
Function Class:^^This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 165 of file nil/include/chsem.h.
Referenced by chGuardedPoolAllocI().
chSemFastSignalI
#define chSemFastSignalI (sp) ((sp)->cnt++)
Increases the semaphore counter.
This macro can be used when the counter is known to be not negative.
Parameters
[in] sp pointer to a semaphore_t structure
Function Class:^^This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 176 of file nil/include/chsem.h.
chSemGetCounterI
#define chSemGetCounterI (sp) ((sp)->cnt)
Returns the semaphore counter current value.
Function Class:^^This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 183 of file nil/include/chsem.h.
Referenced by chGuardedPoolAllocI(), and chGuardedPoolGetCounterI().
Function Documentation
chSemWaitTimeout()
msg_t chSemWaitTimeout (semaphore_t * sp, sysinterval_t timeout)
Performs a wait operation on a semaphore with timeout specification.
Parameters
[in] sp pointer to a semaphore_t structure
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
NIL_MSG_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
NIL_MSG_RST if the semaphore has been reset using chSemReset().
NIL_MSG_TMO if the semaphore has not been signaled or reset within the specified timeout.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 75 of file nil/src/chsem.c.
References chSemWaitTimeoutS(), chSysLock, and chSysUnlock.
chSemWaitTimeoutS()
msg_t chSemWaitTimeoutS (semaphore_t * sp, sysinterval_t timeout)
Performs a wait operation on a semaphore with timeout specification.
Parameters
[in] sp pointer to a semaphore_t structure
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
NIL_MSG_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
NIL_MSG_RST if the semaphore has been reset using chSemReset().
NIL_MSG_TMO if the semaphore has not been signaled or reset within the specified timeout.
Function Class:^^This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 104 of file nil/src/chsem.c.
Referenced by chSemWaitTimeout().
chSemSignal()
void chSemSignal (semaphore_t * sp)
Performs a signal operation on a semaphore.
Parameters
[in] sp pointer to a semaphore_t structure
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 134 of file nil/src/chsem.c.
References chSchRescheduleS(), chSemSignalI(), chSysLock, and chSysUnlock.
chSemSignalI()
void chSemSignalI (semaphore_t * sp)
Performs a signal operation on a semaphore.
Postcondition
This function does not reschedule so a call to a rescheduling function must be performed before unlocking the kernel. Note that interrupt handlers always reschedule on exit so an explicit reschedule must not be performed in ISRs.
Parameters
[in] sp pointer to a semaphore_t structure
Function Class:^^This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 153 of file nil/src/chsem.c.
Referenced by chSemSignal().
chSemResetWithMessage()
void chSemResetWithMessage (semaphore_t * sp, cnt_t n, msg_t msg)
Performs a reset operation on the semaphore.
Postcondition
After invoking this function all the threads waiting on the semaphore, if any, are released and the semaphore counter is set to the specified, non negative, value.
This function does not reschedule so a call to a rescheduling function must be performed before unlocking the kernel. Note that interrupt handlers always reschedule on exit so an explicit reschedule must not be performed in ISRs.
Parameters
[in] sp pointer to a semaphore_t structure
[in] n the new value of the semaphore counter. The value must be non-negative.
[in] msg message to be sent
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 184 of file nil/src/chsem.c.
References chSchRescheduleS(), chSemResetWithMessageI(), chSysLock, and chSysUnlock.
chSemResetWithMessageI()
void chSemResetWithMessageI (semaphore_t * sp, cnt_t n, msg_t msg)
Performs a reset operation on the semaphore.
Postcondition
After invoking this function all the threads waiting on the semaphore, if any, are released and the semaphore counter is set to the specified, non negative, value.
This function does not reschedule so a call to a rescheduling function must be performed before unlocking the kernel. Note that interrupt handlers always reschedule on exit so an explicit reschedule must not be performed in ISRs.
Parameters
[in] sp pointer to a semaphore_t structure
[in] n the new value of the semaphore counter. The value must be non-negative.
[in] msg message to be sent
Function Class:^^This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 209 of file nil/src/chsem.c.
Referenced by chSemResetWithMessage().